name: arabakiralama
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  http: ^0.13.3
  intl: ^0.17.0
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

